version: '3'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./etc/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    restart: unless-stopped
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - monitoring
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./etc/log:/var/log
      - ./etc/promtail:/etc/promtail
    restart: unless-stopped
    command:
      - "--config.file=/etc/promtail/promtail-config.yml"
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./etc/loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: 
      - "--config.file=/etc/loki/loki-config.yml"
    networks:
      - monitoring

  backend:
    build:
      context: .
      target: backend
    container_name: backend
    command: pm2-runtime etc/pm2/process.yml
    volumes:
      - ./etc/log:/usr/src/api/log
      - ./storage:/usr/src/api/storage
    environment:
      - DOCKER=true
    expose:
      - 9000
    links:
      - database
    ports:
      - "9000:9000"
    networks:
      - monitoring
  
  database:
    container_name: database
    image: mongo
    command: mongod --port 27000
    expose:
      - 27000
    ports:
      - "27000:27000"
    networks:
      - monitoring

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - monitoring